### ISSUE TITLE
Test if AKS virtual nodes has any value

### ISSUE THREAD

**Issue by duckie** [dataiku/dss-plugin-aks-clusters#41]
AKS virtual node is the Azure equivalent of Fargate for EKS (AWS) or GKE Autopilot (GCP).  It could be interesting for this plugins if the startup time is not too slow.

https://docs.microsoft.com/en-us/azure/aks/virtual-nodes-portal

**Comment by thtrunck** [comment]
Moving that to our internal backlog. And closing it here (note that given the current demand we do not plan to do that soon)
