### ISSUE TITLE
Update with new icon

### ISSUE THREAD

**Issue by alexcombessie** [dataiku/dss-plugin-aks-clusters#6]
A new icon is available in master:
https://github.com/dataiku/dip/blob/8a329c743447e5394f04cc78dbc54c67fe7c53c2/src/main/platypus/static/dataiku/css/font.less#L1540

To guarantee back-compatibility, you can use this syntax
"icon": "icon-azure-kubernetes-services icon-cloud"

**Comment by alexcombessie** [comment]
👋  @hrjn  (small UX thing)

**Comment by hrjn** [comment]
@alexcombessie noted, I'll add that to the next few updates we make to the plugin, thanks!

**Comment by alexcombessie** [comment]
Hello @jbelafa @hrjn! 
Any chance we can use our custom icon (comes with DSS8)? 
Cheers,
Alex

**Comment by hrjn** [comment]
I haven't forgotten you @alexcombessie :D New icon will pop up when merging #14

**Comment by hrjn** [comment]
[Done. ](https://github.com/dataiku/dss-plugin-aks-clusters/commit/82d8fdad9e34c53b5ecfdb19ba5ae5f0f4d5df38)
